

DROP PROCEDURE IF EXISTS `migration_sim_bulk_insert`;
DELIMITER //
CREATE PROCEDURE `migration_sim_bulk_insert`()
BEGIN



DECLARE EXIT handler FOR SQLEXCEPTION
BEGIN

GET DIAGNOSTICS CONDITION 1
@p1 = RETURNED_SQLSTATE, @p2 = MESSAGE_TEXT;
SELECT DATABASE(), CONCAT(@p1 , @p2) INTO @database, @MESSAGE_TEXT;

SET @error_history = CONCAT("INSERT INTO migration_tracking_history(database_name,query_print,create_date, message_status) SELECT '",@database,"',0, now() ,'",@MESSAGE_TEXT,"';");

SELECT COUNT(1) INTO @before_excution FROM assets;
SELECT CONCAT('before_excution: ',IFNULL(@before_excution,0)) as before_excution,
CONCAT('after_execution: ',IFNULL(@before_excution,0)) as after_execution,
CONCAT('success_count: ',0) as success_count,
CONCAT('failed_count: ',0) as failed_count,
IFNULL(@MESSAGE_TEXT,'') as Remarks;

PREPARE stmt_1 FROM @error_history;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;
  ROLLBACK;
END ;

SET @cntsimtype=NULL;
SET @cntsimcategory=NULL;
SET @cnticcid=NULL;
SET @cntimsi=NULL;
SET @cntmsisdn=NULL;
SET @cntstate=NULL;
SET @cntcountriesid=NULL;
SET @cntdeviceplanid=NULL;
SET @cntentaccountid=NULL;
SET @migrationassetsextended=NULL;
SET @migrationassets=NULL;
SET @before_excution=0;
SET @after_execution=0;
SET @success_count=0;
SET @failed_count_ex=0;
SET @failed_count=0;
SET @MESSAGE_TEXT='';
SET @delete_history='';
SET @Update_history='';
SET @insert_assets_extended='';
SET @insert_assets='';
SET @success_history='';
 SET SESSION group_concat_max_len = 10000000000;
SET @delete_history = CONCAT("DELETE FROM migration_tracking_history WHERE  create_date < DATE_SUB(DATE(NOW()) ,INTERVAL 15 DAY);");

prepare stmt_1 from @delete_history;
execute stmt_1;
deallocate prepare stmt_1;



SET @Update_history = CONCAT("Update migration_tracking_history set is_completed=0;");


prepare stmt_1 from @Update_history;
execute stmt_1;
deallocate prepare stmt_1;


SELECT count(1) INTO @ftotal_count from migration_assets;
SELECT COUNT(1) INTO @before_excution FROM assets;

START TRANSACTION;


TRUNCATE TABLE migration_assets_error_history;
TRUNCATE TABLE migration_assets_extended_error_history;




INSERT INTO migration_assets_extended_error_history (`CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`,`Error_Message`)
SELECT `CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`,'invalid sim_type_id value' from migration_assets_extended WHERE ((sim_type_id NOT in (3,4) OR sim_type_id IS NULL));



INSERT INTO migration_assets_extended_error_history(`CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`,`Error_Message`)
SELECT `CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`,'invalid sim_category value' from migration_assets_extended WHERE ((sim_category NOT in ('831','830','05X') OR sim_category IS NULL));


INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`)
SELECT DISTINCT a.`CREATE_DATE`,a.`ACTIVATION_DATE`,a.`APN`,a.`DATA_USAGE_LIMIT`,a.`DEVICE_ID`,a.`DEVICE_IP_ADDRESS`,a.`DYNAMIC_IMSI`,a.`DONOR_IMSI`,a.`ICCID`,a.`IMEI`,a.`IMSI`,a.`IN_SESSION`,a.`MODEM_ID`,a.`MSISDN`,a.`SESSION_START_TIME`,a.`SMS_USAGE_LIMIT`,a.`STATE`,a.`STATUS`,a.`VOICE_USAGE_LIMIT`,a.`SUBSCRIBER_NAME`,a.`SUBSCRIBER_LAST_NAME`,a.`SUBSCRIBER_GENDER`,a.`SUBSCRIBER_DOB`,a.`ALTERNATE_CONTACT_NUMBER`,a.`SUBSCRIBER_EMAIL`,a.`SUBSCRIBER_ADDRESS`,a.`CUSTOM_PARAM_1`,a.`CUSTOM_PARAM_2`,a.`CUSTOM_PARAM_3`,a.`CUSTOM_PARAM_4`,a.`CUSTOM_PARAM_5`,a.`SERVICE_PLAN_ID`,a.`LOCATION_COVERAGE_ID`,a.`NEXT_LOCATION_COVERAGE_ID`,a.`BILLING_CYCLE`,a.`RATE_PLAN_ID`,a.`NEXT_RATE_PLAN_ID`,a.`MNO_ACCOUNTID`,a.`ENT_ACCOUNTID`,a.`TOTAL_DATA_USAGE`,a.`TOTAL_DATA_DOWNLOAD`,a.`TOTAL_DATA_UPLOAD`,a.`DATA_USAGE_THRESHOLD`,a.`IP_ADDRESS`,a.`LAST_KNOWN_LOCATION`,a.`LAST_KNOWN_NETWORK`,a.`STATE_MODIFIED_DATE`,a.`USAGES_NOTIFICATION`,a.`BSS_ID`,a.`GOUP_ID`,a.`LOCK_REFERENCE`,a.`SIM_POOL_ID`,a.`WHOLESALE_PLAN_ID`,a.`PROFILE_STATE`,a.`EUICC_ID`,a.`OPERATIONAL_PROFILE_DATA_PLAN`,a.`BOOTSTRAP_PROFILE`,a.`CURRENT_IMEI`,a.`ASSETS_EXTENDED_ID`,a.`DEVICE_PLAN_ID`,a.`DEVICE_PLAN_DATE`,a.`COUNTRIES_ID`,a.`DONOR_ICCID`,'invalid countries value' FROM migration_assets AS a LEFT JOIN countries AS c ON TRIM(a.COUNTRIES_ID)=c.NAME WHERE (c.NAME IS NULL OR c.NAME='');


INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`)
SELECT DISTINCT a.`CREATE_DATE`,a.`ACTIVATION_DATE`,a.`APN`,a.`DATA_USAGE_LIMIT`,a.`DEVICE_ID`,a.`DEVICE_IP_ADDRESS`,a.`DYNAMIC_IMSI`,a.`DONOR_IMSI`,a.`ICCID`,a.`IMEI`,a.`IMSI`,a.`IN_SESSION`,a.`MODEM_ID`,a.`MSISDN`,a.`SESSION_START_TIME`,a.`SMS_USAGE_LIMIT`,a.`STATE`,a.`STATUS`,a.`VOICE_USAGE_LIMIT`,a.`SUBSCRIBER_NAME`,a.`SUBSCRIBER_LAST_NAME`,a.`SUBSCRIBER_GENDER`,a.`SUBSCRIBER_DOB`,a.`ALTERNATE_CONTACT_NUMBER`,a.`SUBSCRIBER_EMAIL`,a.`SUBSCRIBER_ADDRESS`,a.`CUSTOM_PARAM_1`,a.`CUSTOM_PARAM_2`,a.`CUSTOM_PARAM_3`,a.`CUSTOM_PARAM_4`,a.`CUSTOM_PARAM_5`,a.`SERVICE_PLAN_ID`,a.`LOCATION_COVERAGE_ID`,a.`NEXT_LOCATION_COVERAGE_ID`,a.`BILLING_CYCLE`,a.`RATE_PLAN_ID`,a.`NEXT_RATE_PLAN_ID`,a.`MNO_ACCOUNTID`,a.`ENT_ACCOUNTID`,a.`TOTAL_DATA_USAGE`,a.`TOTAL_DATA_DOWNLOAD`,a.`TOTAL_DATA_UPLOAD`,a.`DATA_USAGE_THRESHOLD`,a.`IP_ADDRESS`,a.`LAST_KNOWN_LOCATION`,a.`LAST_KNOWN_NETWORK`,a.`STATE_MODIFIED_DATE`,a.`USAGES_NOTIFICATION`,a.`BSS_ID`,a.`GOUP_ID`,a.`LOCK_REFERENCE`,a.`SIM_POOL_ID`,a.`WHOLESALE_PLAN_ID`,a.`PROFILE_STATE`,a.`EUICC_ID`,a.`OPERATIONAL_PROFILE_DATA_PLAN`,a.`BOOTSTRAP_PROFILE`,a.`CURRENT_IMEI`,a.`ASSETS_EXTENDED_ID`,a.`DEVICE_PLAN_ID`,a.`DEVICE_PLAN_DATE`,a.`COUNTRIES_ID`,a.`DONOR_ICCID`,'invalid device plan and account id is not mapping to device plan' FROM migration_assets AS a LEFT JOIN accounts AS b ON TRIM(a.ENT_ACCOUNTID) COLLATE utf8mb4_0900_ai_ci = b.LEGACY_BAN COLLATE utf8mb4_0900_ai_ci LEFT JOIN countries AS c ON TRIM(a.COUNTRIES_ID)=c.NAME LEFT JOIN device_rate_plan AS d ON TRIM(a.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID WHERE (d.PLAN_NAME IS NULL OR d.PLAN_NAME='');


INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`)
SELECT DISTINCT a.`CREATE_DATE`,a.`ACTIVATION_DATE`,a.`APN`,a.`DATA_USAGE_LIMIT`,a.`DEVICE_ID`,a.`DEVICE_IP_ADDRESS`,a.`DYNAMIC_IMSI`,a.`DONOR_IMSI`,a.`ICCID`,a.`IMEI`,a.`IMSI`,a.`IN_SESSION`,a.`MODEM_ID`,a.`MSISDN`,a.`SESSION_START_TIME`,a.`SMS_USAGE_LIMIT`,a.`STATE`,a.`STATUS`,a.`VOICE_USAGE_LIMIT`,a.`SUBSCRIBER_NAME`,a.`SUBSCRIBER_LAST_NAME`,a.`SUBSCRIBER_GENDER`,a.`SUBSCRIBER_DOB`,a.`ALTERNATE_CONTACT_NUMBER`,a.`SUBSCRIBER_EMAIL`,a.`SUBSCRIBER_ADDRESS`,a.`CUSTOM_PARAM_1`,a.`CUSTOM_PARAM_2`,a.`CUSTOM_PARAM_3`,a.`CUSTOM_PARAM_4`,a.`CUSTOM_PARAM_5`,a.`SERVICE_PLAN_ID`,a.`LOCATION_COVERAGE_ID`,a.`NEXT_LOCATION_COVERAGE_ID`,a.`BILLING_CYCLE`,a.`RATE_PLAN_ID`,a.`NEXT_RATE_PLAN_ID`,a.`MNO_ACCOUNTID`,a.`ENT_ACCOUNTID`,a.`TOTAL_DATA_USAGE`,a.`TOTAL_DATA_DOWNLOAD`,a.`TOTAL_DATA_UPLOAD`,a.`DATA_USAGE_THRESHOLD`,a.`IP_ADDRESS`,a.`LAST_KNOWN_LOCATION`,a.`LAST_KNOWN_NETWORK`,a.`STATE_MODIFIED_DATE`,a.`USAGES_NOTIFICATION`,a.`BSS_ID`,a.`GOUP_ID`,a.`LOCK_REFERENCE`,a.`SIM_POOL_ID`,a.`WHOLESALE_PLAN_ID`,a.`PROFILE_STATE`,a.`EUICC_ID`,a.`OPERATIONAL_PROFILE_DATA_PLAN`,a.`BOOTSTRAP_PROFILE`,a.`CURRENT_IMEI`,a.`ASSETS_EXTENDED_ID`,a.`DEVICE_PLAN_ID`,a.`DEVICE_PLAN_DATE`,a.`COUNTRIES_ID`,a.`DONOR_ICCID`,'invalid account value' FROM migration_assets AS a LEFT JOIN accounts AS b ON TRIM(a.ENT_ACCOUNTID) COLLATE utf8mb4_0900_ai_ci = b.LEGACY_BAN COLLATE utf8mb4_0900_ai_ci WHERE (b.NAME IS NULL OR b.NAME='');

INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`)
SELECT DISTINCT a.`CREATE_DATE`,a.`ACTIVATION_DATE`,a.`APN`,a.`DATA_USAGE_LIMIT`,a.`DEVICE_ID`,a.`DEVICE_IP_ADDRESS`,a.`DYNAMIC_IMSI`,a.`DONOR_IMSI`,a.`ICCID`,a.`IMEI`,a.`IMSI`,a.`IN_SESSION`,a.`MODEM_ID`,a.`MSISDN`,a.`SESSION_START_TIME`,a.`SMS_USAGE_LIMIT`,a.`STATE`,a.`STATUS`,a.`VOICE_USAGE_LIMIT`,a.`SUBSCRIBER_NAME`,a.`SUBSCRIBER_LAST_NAME`,a.`SUBSCRIBER_GENDER`,a.`SUBSCRIBER_DOB`,a.`ALTERNATE_CONTACT_NUMBER`,a.`SUBSCRIBER_EMAIL`,a.`SUBSCRIBER_ADDRESS`,a.`CUSTOM_PARAM_1`,a.`CUSTOM_PARAM_2`,a.`CUSTOM_PARAM_3`,a.`CUSTOM_PARAM_4`,a.`CUSTOM_PARAM_5`,a.`SERVICE_PLAN_ID`,a.`LOCATION_COVERAGE_ID`,a.`NEXT_LOCATION_COVERAGE_ID`,a.`BILLING_CYCLE`,a.`RATE_PLAN_ID`,a.`NEXT_RATE_PLAN_ID`,a.`MNO_ACCOUNTID`,a.`ENT_ACCOUNTID`,a.`TOTAL_DATA_USAGE`,a.`TOTAL_DATA_DOWNLOAD`,a.`TOTAL_DATA_UPLOAD`,a.`DATA_USAGE_THRESHOLD`,a.`IP_ADDRESS`,a.`LAST_KNOWN_LOCATION`,a.`LAST_KNOWN_NETWORK`,a.`STATE_MODIFIED_DATE`,a.`USAGES_NOTIFICATION`,a.`BSS_ID`,a.`GOUP_ID`,a.`LOCK_REFERENCE`,a.`SIM_POOL_ID`,a.`WHOLESALE_PLAN_ID`,a.`PROFILE_STATE`,a.`EUICC_ID`,a.`OPERATIONAL_PROFILE_DATA_PLAN`,a.`BOOTSTRAP_PROFILE`,a.`CURRENT_IMEI`,a.`ASSETS_EXTENDED_ID`,a.`DEVICE_PLAN_ID`,a.`DEVICE_PLAN_DATE`,a.`COUNTRIES_ID`,a.`DONOR_ICCID`,'Existing Duplicate records failed' from migration_assets a WHERE IMSI IN (SELECT DISTINCT IMSI FROM ASSETS) ;

INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`)
SELECT DISTINCT a.`CREATE_DATE`,a.`ACTIVATION_DATE`,a.`APN`,a.`DATA_USAGE_LIMIT`,a.`DEVICE_ID`,a.`DEVICE_IP_ADDRESS`,a.`DYNAMIC_IMSI`,a.`DONOR_IMSI`,a.`ICCID`,a.`IMEI`,a.`IMSI`,a.`IN_SESSION`,a.`MODEM_ID`,a.`MSISDN`,a.`SESSION_START_TIME`,a.`SMS_USAGE_LIMIT`,a.`STATE`,a.`STATUS`,a.`VOICE_USAGE_LIMIT`,a.`SUBSCRIBER_NAME`,a.`SUBSCRIBER_LAST_NAME`,a.`SUBSCRIBER_GENDER`,a.`SUBSCRIBER_DOB`,a.`ALTERNATE_CONTACT_NUMBER`,a.`SUBSCRIBER_EMAIL`,a.`SUBSCRIBER_ADDRESS`,a.`CUSTOM_PARAM_1`,a.`CUSTOM_PARAM_2`,a.`CUSTOM_PARAM_3`,a.`CUSTOM_PARAM_4`,a.`CUSTOM_PARAM_5`,a.`SERVICE_PLAN_ID`,a.`LOCATION_COVERAGE_ID`,a.`NEXT_LOCATION_COVERAGE_ID`,a.`BILLING_CYCLE`,a.`RATE_PLAN_ID`,a.`NEXT_RATE_PLAN_ID`,a.`MNO_ACCOUNTID`,a.`ENT_ACCOUNTID`,a.`TOTAL_DATA_USAGE`,a.`TOTAL_DATA_DOWNLOAD`,a.`TOTAL_DATA_UPLOAD`,a.`DATA_USAGE_THRESHOLD`,a.`IP_ADDRESS`,a.`LAST_KNOWN_LOCATION`,a.`LAST_KNOWN_NETWORK`,a.`STATE_MODIFIED_DATE`,a.`USAGES_NOTIFICATION`,a.`BSS_ID`,a.`GOUP_ID`,a.`LOCK_REFERENCE`,a.`SIM_POOL_ID`,a.`WHOLESALE_PLAN_ID`,a.`PROFILE_STATE`,a.`EUICC_ID`,a.`OPERATIONAL_PROFILE_DATA_PLAN`,a.`BOOTSTRAP_PROFILE`,a.`CURRENT_IMEI`,a.`ASSETS_EXTENDED_ID`,a.`DEVICE_PLAN_ID`,a.`DEVICE_PLAN_DATE`,a.`COUNTRIES_ID`,a.`DONOR_ICCID`,'Existing Duplicate records failed' from migration_assets a WHERE ICCID IN (SELECT DISTINCT ICCID FROM ASSETS) ;

INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`)
SELECT DISTINCT a.`CREATE_DATE`,a.`ACTIVATION_DATE`,a.`APN`,a.`DATA_USAGE_LIMIT`,a.`DEVICE_ID`,a.`DEVICE_IP_ADDRESS`,a.`DYNAMIC_IMSI`,a.`DONOR_IMSI`,a.`ICCID`,a.`IMEI`,a.`IMSI`,a.`IN_SESSION`,a.`MODEM_ID`,a.`MSISDN`,a.`SESSION_START_TIME`,a.`SMS_USAGE_LIMIT`,a.`STATE`,a.`STATUS`,a.`VOICE_USAGE_LIMIT`,a.`SUBSCRIBER_NAME`,a.`SUBSCRIBER_LAST_NAME`,a.`SUBSCRIBER_GENDER`,a.`SUBSCRIBER_DOB`,a.`ALTERNATE_CONTACT_NUMBER`,a.`SUBSCRIBER_EMAIL`,a.`SUBSCRIBER_ADDRESS`,a.`CUSTOM_PARAM_1`,a.`CUSTOM_PARAM_2`,a.`CUSTOM_PARAM_3`,a.`CUSTOM_PARAM_4`,a.`CUSTOM_PARAM_5`,a.`SERVICE_PLAN_ID`,a.`LOCATION_COVERAGE_ID`,a.`NEXT_LOCATION_COVERAGE_ID`,a.`BILLING_CYCLE`,a.`RATE_PLAN_ID`,a.`NEXT_RATE_PLAN_ID`,a.`MNO_ACCOUNTID`,a.`ENT_ACCOUNTID`,a.`TOTAL_DATA_USAGE`,a.`TOTAL_DATA_DOWNLOAD`,a.`TOTAL_DATA_UPLOAD`,a.`DATA_USAGE_THRESHOLD`,a.`IP_ADDRESS`,a.`LAST_KNOWN_LOCATION`,a.`LAST_KNOWN_NETWORK`,a.`STATE_MODIFIED_DATE`,a.`USAGES_NOTIFICATION`,a.`BSS_ID`,a.`GOUP_ID`,a.`LOCK_REFERENCE`,a.`SIM_POOL_ID`,a.`WHOLESALE_PLAN_ID`,a.`PROFILE_STATE`,a.`EUICC_ID`,a.`OPERATIONAL_PROFILE_DATA_PLAN`,a.`BOOTSTRAP_PROFILE`,a.`CURRENT_IMEI`,a.`ASSETS_EXTENDED_ID`,a.`DEVICE_PLAN_ID`,a.`DEVICE_PLAN_DATE`,a.`COUNTRIES_ID`,a.`DONOR_ICCID`,'Existing Duplicate records failed' from migration_assets a WHERE MSISDN IN (SELECT DISTINCT MSISDN FROM ASSETS) ;




SET FOREIGN_KEY_CHECKS=0;



DROP TEMPORARY TABLE IF EXISTS `temp_assets_duplicate`;
CREATE temporary TABLE `temp_assets_duplicate` (`id` int);


INSERT INTO temp_assets_duplicate(id) SELECT DISTINCT id
FROM migration_assets WHERE imsi IN (SELECT imsi FROM assets);

INSERT INTO temp_assets_duplicate(id) SELECT DISTINCT id
FROM migration_assets WHERE MSISDN  IN (SELECT MSISDN FROM assets);

INSERT INTO temp_assets_duplicate(id) SELECT DISTINCT id
FROM migration_assets WHERE ICCID  IN (SELECT ICCID FROM assets);


DELETE FROM migration_assets WHERE ID IN (SELECT id FROM temp_assets_duplicate);

COMMIT;



SET FOREIGN_KEY_CHECKS=1;



SELECT count(1) into @migrationassets from migration_assets WHERE ID NOT IN (SELECT ID FROM assets);
SELECT count(1) into @migrationassetsextended from migration_assets_extended WHERE migration_assets_extended.ID IN (SELECT migration_assets.ASSETS_EXTENDED_ID FROM migration_assets);


IF(@migrationassetsextended>0 AND @migrationassets>0)
THEN


SET FOREIGN_KEY_CHECKS=0;
SET @insert_assets_extended = CONCAT("INSERT INTO assets_extended(ID, `CREATE_DATE`, `voice_template`, `sms_template`, `data_template`, `sim_type_id`, `ORDER_NUMBER`, `SERVICE_GRANT`, `IMEI_LOCK`, `OLD_PROFILE_STATE`, `CURRENT_PROFILE_STATE`, `custom_param_1`, `custom_param_2`, `custom_param_3`, `custom_param_4`, `custom_param_5`, `BULK_SERVICE_NAME`, `FVS_DATA`, `sim_category`,migrate_from) SELECT ID,`CREATE_DATE`, `voice_template`, `sms_template`, `data_template`, `sim_type_id`, `ORDER_NUMBER`, `SERVICE_GRANT`, `IMEI_LOCK`, `OLD_PROFILE_STATE`, `CURRENT_PROFILE_STATE`, `custom_param_1`, `custom_param_2`, `custom_param_3`, `custom_param_4`, `custom_param_5`, `BULK_SERVICE_NAME`, `FVS_DATA`, `sim_category`,'MIGRATED' FROM migration_assets_extended  WHERE ID IN (SELECT migration_assets.ASSETS_EXTENDED_ID FROM migration_assets);");

PREPARE stmt_1 FROM @insert_assets_extended;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;



SET @insert_assets = CONCAT("INSERT INTO assets(ID,`CREATE_DATE`, `ACTIVATION_DATE`, `APN`, `DATA_USAGE_LIMIT`, `DEVICE_ID`, `DEVICE_IP_ADDRESS`, `DYNAMIC_IMSI`, `DONOR_IMSI`, `ICCID`, `IMEI`, `IMSI`, `IN_SESSION`, `MODEM_ID`, `MSISDN`, `SESSION_START_TIME`, `SMS_USAGE_LIMIT`, `STATE`, `STATUS`, `VOICE_USAGE_LIMIT`, `SUBSCRIBER_NAME`, `SUBSCRIBER_LAST_NAME`, `SUBSCRIBER_GENDER`, `SUBSCRIBER_DOB`, `ALTERNATE_CONTACT_NUMBER`, `SUBSCRIBER_EMAIL`, `SUBSCRIBER_ADDRESS`, `CUSTOM_PARAM_1`, `CUSTOM_PARAM_2`, `CUSTOM_PARAM_3`, `CUSTOM_PARAM_4`, `CUSTOM_PARAM_5`, `SERVICE_PLAN_ID`, `LOCATION_COVERAGE_ID`, `NEXT_LOCATION_COVERAGE_ID`, `BILLING_CYCLE`, `RATE_PLAN_ID`, `NEXT_RATE_PLAN_ID`, `MNO_ACCOUNTID`, `ENT_ACCOUNTID`, `TOTAL_DATA_USAGE`, `TOTAL_DATA_DOWNLOAD`, `TOTAL_DATA_UPLOAD`, `DATA_USAGE_THRESHOLD`, `IP_ADDRESS`, `LAST_KNOWN_LOCATION`, `LAST_KNOWN_NETWORK`, `STATE_MODIFIED_DATE`, `USAGES_NOTIFICATION`, `BSS_ID`, `GOUP_ID`, `LOCK_REFERENCE`, `SIM_POOL_ID`, `WHOLESALE_PLAN_ID`, `PROFILE_STATE`, `EUICC_ID`, `OPERATIONAL_PROFILE_DATA_PLAN`, `BOOTSTRAP_PROFILE`, `CURRENT_IMEI`, `ASSETS_EXTENDED_ID`, `DEVICE_PLAN_ID`, `DEVICE_PLAN_DATE`, `COUNTRIES_ID`, `DONOR_ICCID`) SELECT assets.ID, IFNULL(`assets`.`CREATE_DATE`,NOW()), `assets`.`ACTIVATION_DATE`, `assets`.`APN`, `assets`.`DATA_USAGE_LIMIT`, `assets`.`DEVICE_ID`, `assets`.`DEVICE_IP_ADDRESS`, `assets`.`DYNAMIC_IMSI`, `assets`.`DONOR_IMSI`, `assets`.`ICCID`, `assets`.`IMEI`, `assets`.`IMSI`, IFNULL(`assets`.`IN_SESSION`,0), `assets`.`MODEM_ID`, `assets`.`MSISDN`, `assets`.`SESSION_START_TIME`, `assets`.`SMS_USAGE_LIMIT`, IFNULL(`assets`.`STATE`,'Activated'), IFNULL(`assets`.`STATUS`,'Activated'), `assets`.`VOICE_USAGE_LIMIT`, `assets`.`SUBSCRIBER_NAME`, `assets`.`SUBSCRIBER_LAST_NAME`, IFNULL(`assets`.`SUBSCRIBER_GENDER`,0), `assets`.`SUBSCRIBER_DOB`, `assets`.`ALTERNATE_CONTACT_NUMBER`, `assets`.`SUBSCRIBER_EMAIL`, `assets`.`SUBSCRIBER_ADDRESS`, `assets`.`CUSTOM_PARAM_1`, `assets`.`CUSTOM_PARAM_2`, `assets`.`CUSTOM_PARAM_3`, `assets`.`CUSTOM_PARAM_4`, `assets`.`CUSTOM_PARAM_5`, e.SERVICE_PLAN_ID, `assets`.`LOCATION_COVERAGE_ID`, IFNULL(`assets`.`NEXT_LOCATION_COVERAGE_ID`,0), IFNULL(`assets`.`BILLING_CYCLE`,1), `assets`.`RATE_PLAN_ID`, `assets`.`NEXT_RATE_PLAN_ID`, (SELECT ID FROM accounts WHERE TYPE=3 AND NAME='KSA_OPCO' AND DELETED=0), `b`.`id`, IFNULL(`assets`.`TOTAL_DATA_USAGE`,0), IFNULL(`assets`.`TOTAL_DATA_DOWNLOAD`,0), IFNULL(`assets`.`TOTAL_DATA_UPLOAD`,0), IFNULL(`assets`.`DATA_USAGE_THRESHOLD`,0), `assets`.`IP_ADDRESS`, `assets`.`LAST_KNOWN_LOCATION`, `assets`.`LAST_KNOWN_NETWORK`, IFNULL(`assets`.`STATE_MODIFIED_DATE`,NOW()), IFNULL(`assets`.`USAGES_NOTIFICATION`,0), `assets`.`BSS_ID`, `assets`.`GOUP_ID`, `assets`.`LOCK_REFERENCE`, `assets`.`SIM_POOL_ID`, `assets`.`WHOLESALE_PLAN_ID`, `assets`.`PROFILE_STATE`, `assets`.`EUICC_ID`, `assets`.`OPERATIONAL_PROFILE_DATA_PLAN`, `assets`.`BOOTSTRAP_PROFILE`, `assets`.`CURRENT_IMEI`, `assets`.`ASSETS_EXTENDED_ID`, `d`.`id`, IFNULL(`assets`.`DEVICE_PLAN_DATE`,NOW()), `c`.`ID`, `assets`.`DONOR_ICCID` FROM migration_assets AS assets INNER JOIN accounts AS b ON TRIM(assets.ENT_ACCOUNTID)=b.LEGACY_BAN AND b.DELETED=0 INNER JOIN countries AS c ON TRIM(assets.COUNTRIES_ID)=c.NAME LEFT JOIN device_rate_plan AS d ON TRIM(assets.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID AND d.DELETED=0 LEFT JOIN device_service_plan_mapping as e on e.DEVICE_PLAN_ID=d.id WHERE assets.ID NOT IN (SELECT ID FROM assets);");

PREPARE stmt_1 FROM @insert_assets;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

COMMIT;
SET FOREIGN_KEY_CHECKS=1;

SET @delete_assets_extended = CONCAT("DELETE FROM assets_extended WHERE ID NOT IN (SELECT ASSETS_EXTENDED_ID FROM assets);");

PREPARE stmt_1 FROM @delete_assets_extended;
EXECUTE stmt_1;
DEALLOCATE PREPARE stmt_1;

SELECT count(1) INTO @success_count from assets WHERE ID IN (SELECT ID FROM migration_assets);

ELSEIF(@migrationassets=0 AND @migrationassetsextended=0) THEN

SELECT 'No Records Found in migration_assets and migration_assets_extended table' INTO @MESSAGE_TEXT;

SET @error_history = CONCAT("INSERT INTO migration_tracking_history(database_name,query_print,create_date, message_status,is_completed) SELECT
DATABASE(),'failure',now(),'",@MESSAGE_TEXT,"',1;");

PREPARE stmt_1 FROM @error_history;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;
END IF;

SELECT count(1) INTO @failed_count from migration_assets WHERE ID NOT IN (SELECT ID FROM assets);
SELECT COUNT(1) INTO @after_execution FROM assets;


IF(@after_execution>@before_excution) THEN
SET FOREIGN_KEY_CHECKS=0;



DROP TEMPORARY TABLE IF EXISTS temp_migration_apn_ip_account_list;
CREATE TEMPORARY TABLE IF NOT EXISTS `temp_migration_apn_ip_account_list` (
   id bigint NOT NULL AUTO_INCREMENT,
   account_id bigint DEFAULT NULL,
   apn_id bigint DEFAULT NULL,
   ip_id bigint DEFAULT NULL,
   create_date datetime DEFAULT NULL,
   asset_id  bigint DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

INSERT INTO temp_migration_apn_ip_account_list(account_id,apn_id,ip_id,create_date,asset_id)
SELECT distinct b.id as account_id,f.apn_id,f.ID as ip_id,NOW() as create_date,assets.ID as asset_id FROM migration_assets assets INNER JOIN accounts AS b ON TRIM(assets.ENT_ACCOUNTID)=b.LEGACY_BAN AND b.DELETED=0 INNER JOIN device_rate_plan AS d ON TRIM(assets.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID AND d.DELETED=0 INNER JOIN device_plan_to_service_apn_mapping as e on e.DEVICE_PLAN_ID_ID=d.ID INNER JOIN Service_Apn_ip as f on assets.IP_ADDRESS=f.APN_IP;

INSERT INTO service_apn_account_mapping(ACCOUNT_ID,APN_ID,CREATE_DATE)
SELECT distinct account_id,apn_id,create_date FROM temp_migration_apn_ip_account_list WHERE (account_id NOT IN (SELECT ACCOUNT_ID FROM service_apn_account_mapping) AND apn_id NOT IN (SELECT APN_ID FROM service_apn_account_mapping));

INSERT INTO apn_ip_mapping(APN_ID,IP_ID,CREATE_DATE,ASSETS_ID)
SELECT distinct apn_id,ip_id,create_date,asset_id FROM temp_migration_apn_ip_account_list WHERE
asset_id NOT IN (SELECT DISTINCT ASSETS_ID FROM apn_ip_mapping);

INSERT INTO assets_apn_allocation(ASSETS_ID,APN_ID,CREATE_DATE)
SELECT distinct asset_id,apn_id,create_date FROM temp_migration_apn_ip_account_list WHERE asset_id NOT IN (SELECT DISTINCT ASSETS_ID FROM assets_apn_allocation);

COMMIT;

SET @getsapndet_list = CONCAT("SELECT IFNULL(GROUP_CONCAT(distinct apn_id),0) INTO @sapndet_list FROM temp_migration_apn_ip_account_list");

PREPARE stmt_1 FROM @getsapndet_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

COMMIT;

SET @updsapndet_list = CONCAT("UPDATE service_apn_details as sad SET sad.status='IN_USE' WHERE sad.ID IN (",@sapndet_list,")  AND (sad.status='NOT_IN_USE' OR sad.status IS NULL);");

PREPARE stmt_1 FROM @updsapndet_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SET @getspi_list = CONCAT("SELECT IFNULL(GROUP_CONCAT(distinct ip_id),0) INTO @spi_list FROM temp_migration_apn_ip_account_list");

PREPARE stmt_1 FROM @getspi_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SET @updgetspi_list = CONCAT("UPDATE Service_Apn_ip as sp SET sp.isUse=1 WHERE sp.ID IN (",@spi_list,")  AND (sp.isUse=0 OR sp.isUse IS NULL)");

PREPARE stmt_1 FROM @updgetspi_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SET @getdp_list = CONCAT("SELECT IFNULL(GROUP_CONCAT(distinct account_id),0) INTO @dp_list FROM temp_migration_apn_ip_account_list");

PREPARE stmt_1 FROM @getdp_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SET @upddp_list = CONCAT("UPDATE device_rate_plan as dp SET dp.STATUS=1 WHERE dp.account_id IN (",@dp_list,") AND (dp.STATUS=0 OR dp.STATUS IS NULL);");

PREPARE stmt_1 FROM @upddp_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SET FOREIGN_KEY_CHECKS=1;


SET @ai := (select max(id)+1 from assets);
set @qry = concat('alter table assets auto_increment=',@ai);
prepare stmt from @qry; execute stmt;

SET @aiex := (select max(id)+1 from assets_extended);
set @qryex = concat('alter table assets_extended auto_increment=',@aiex);
prepare stmt from @qryex; execute stmt;

COMMIT;

DELETE n1 FROM service_apn_account_mapping n1, service_apn_account_mapping n2 WHERE n1.id < n2.id AND n1.ACCOUNT_ID = n2.ACCOUNT_ID AND n1.APN_ID = n2.APN_ID ;

END IF;

SELECT CONCAT('before_excution: ',IFNULL(@before_excution,0)) as before_excution,
CONCAT('after_execution: ',IFNULL(@after_execution,0)) as after_execution,
CONCAT('success_count: ',IFNULL(@success_count,0)) as success_count,
CONCAT('failed_count: ',(IFNULL(@ftotal_count,0)-IFNULL(@success_count,0))) as failed_count,
IFNULL(@MESSAGE_TEXT,'') as Remarks;


END //
DELIMITER ;


DROP TABLE IF EXISTS `migration_assets_error_history` ;
CREATE TABLE `migration_assets_error_history` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CREATE_DATE` datetime NOT NULL,
  `ACTIVATION_DATE` datetime DEFAULT NULL,
  `APN` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DATA_USAGE_LIMIT` bigint DEFAULT NULL,
  `DEVICE_ID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DEVICE_IP_ADDRESS` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DYNAMIC_IMSI` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DONOR_IMSI` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ICCID` varchar(25) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `IMEI` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `IMSI` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `IN_SESSION` tinyint(1) DEFAULT '0',
  `MODEM_ID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `MSISDN` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SESSION_START_TIME` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SMS_USAGE_LIMIT` bigint DEFAULT NULL,
  `STATE` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `STATUS` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `VOICE_USAGE_LIMIT` bigint DEFAULT NULL,
  `SUBSCRIBER_NAME` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SUBSCRIBER_LAST_NAME` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SUBSCRIBER_GENDER` tinyint DEFAULT '0',
  `SUBSCRIBER_DOB` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ALTERNATE_CONTACT_NUMBER` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SUBSCRIBER_EMAIL` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SUBSCRIBER_ADDRESS` varchar(556) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CUSTOM_PARAM_1` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CUSTOM_PARAM_2` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CUSTOM_PARAM_3` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CUSTOM_PARAM_4` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CUSTOM_PARAM_5` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SERVICE_PLAN_ID` bigint DEFAULT NULL,
  `LOCATION_COVERAGE_ID` bigint DEFAULT NULL,
  `NEXT_LOCATION_COVERAGE_ID` bigint DEFAULT '0',
  `BILLING_CYCLE` bigint DEFAULT NULL,
  `RATE_PLAN_ID` bigint DEFAULT NULL,
  `NEXT_RATE_PLAN_ID` bigint DEFAULT NULL,
  `MNO_ACCOUNTID` bigint DEFAULT NULL,
  `ENT_ACCOUNTID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TOTAL_DATA_USAGE` double DEFAULT '0',
  `TOTAL_DATA_DOWNLOAD` bigint DEFAULT '0',
  `TOTAL_DATA_UPLOAD` bigint DEFAULT '0',
  `DATA_USAGE_THRESHOLD` bigint DEFAULT '0',
  `IP_ADDRESS` varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '000.000.000.000',
  `LAST_KNOWN_LOCATION` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `LAST_KNOWN_NETWORK` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `STATE_MODIFIED_DATE` datetime DEFAULT NULL,
  `USAGES_NOTIFICATION` tinyint(1) DEFAULT '0',
  `BSS_ID` bigint DEFAULT NULL,
  `GOUP_ID` bigint DEFAULT NULL,
  `LOCK_REFERENCE` varchar(25) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SIM_POOL_ID` bigint DEFAULT NULL,
  `WHOLESALE_PLAN_ID` bigint DEFAULT NULL,
  `PROFILE_STATE` varchar(25) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `EUICC_ID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `OPERATIONAL_PROFILE_DATA_PLAN` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `BOOTSTRAP_PROFILE` int DEFAULT NULL,
  `CURRENT_IMEI` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ASSETS_EXTENDED_ID` bigint DEFAULT NULL,
  `DEVICE_PLAN_ID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DEVICE_PLAN_DATE` timestamp NULL DEFAULT NULL,
  `COUNTRIES_ID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DONOR_ICCID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'For handling luhn digit storing iccid',
  `Error_Message` text COLLATE utf8mb4_general_ci,
  `EXT_METADATA` longtext COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB ;

DROP TABLE IF EXISTS `migration_assets`;
CREATE TABLE `migration_assets` (
  `ID` bigint DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `ACTIVATION_DATE` datetime DEFAULT NULL,
  `APN` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DATA_USAGE_LIMIT` bigint DEFAULT NULL,
  `DEVICE_ID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DEVICE_IP_ADDRESS` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DYNAMIC_IMSI` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DONOR_IMSI` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ICCID` varchar(25) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `IMEI` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `IMSI` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `IN_SESSION` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `MODEM_ID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `MSISDN` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SESSION_START_TIME` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SMS_USAGE_LIMIT` bigint DEFAULT NULL,
  `STATE` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `STATUS` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `VOICE_USAGE_LIMIT` bigint DEFAULT NULL,
  `SUBSCRIBER_NAME` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SUBSCRIBER_LAST_NAME` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SUBSCRIBER_GENDER` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SUBSCRIBER_DOB` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ALTERNATE_CONTACT_NUMBER` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SUBSCRIBER_EMAIL` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SUBSCRIBER_ADDRESS` varchar(556) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CUSTOM_PARAM_1` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CUSTOM_PARAM_2` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CUSTOM_PARAM_3` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CUSTOM_PARAM_4` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CUSTOM_PARAM_5` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SERVICE_PLAN_ID` bigint DEFAULT NULL,
  `LOCATION_COVERAGE_ID` bigint DEFAULT NULL,
  `NEXT_LOCATION_COVERAGE_ID` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `BILLING_CYCLE` bigint DEFAULT NULL,
  `RATE_PLAN_ID` bigint DEFAULT NULL,
  `NEXT_RATE_PLAN_ID` bigint DEFAULT NULL,
  `MNO_ACCOUNTID` bigint DEFAULT NULL,
  `ENT_ACCOUNTID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TOTAL_DATA_USAGE` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TOTAL_DATA_DOWNLOAD` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `TOTAL_DATA_UPLOAD` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DATA_USAGE_THRESHOLD` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `IP_ADDRESS` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `LAST_KNOWN_LOCATION` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `LAST_KNOWN_NETWORK` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `STATE_MODIFIED_DATE` datetime DEFAULT NULL,
  `USAGES_NOTIFICATION` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `BSS_ID` bigint DEFAULT NULL,
  `GOUP_ID` bigint DEFAULT NULL,
  `LOCK_REFERENCE` varchar(25) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SIM_POOL_ID` bigint DEFAULT NULL,
  `WHOLESALE_PLAN_ID` bigint DEFAULT NULL,
  `PROFILE_STATE` varchar(25) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `EUICC_ID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `OPERATIONAL_PROFILE_DATA_PLAN` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `BOOTSTRAP_PROFILE` int DEFAULT NULL,
  `CURRENT_IMEI` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ASSETS_EXTENDED_ID` bigint DEFAULT NULL,
  `DEVICE_PLAN_ID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DEVICE_PLAN_DATE` timestamp NULL DEFAULT NULL,
  `COUNTRIES_ID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `DONOR_ICCID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'For handling luhn digit concept storing iccid',
  `EXT_METADATA` longtext COLLATE utf8mb4_general_ci
) ENGINE=InnoDB ;


DROP TABLE IF EXISTS `migration_assets_extended_error_history`;
CREATE TABLE `migration_assets_extended_error_history` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CREATE_DATE` datetime NOT NULL,
  `voice_template` int DEFAULT NULL,
  `sms_template` int DEFAULT NULL,
  `data_template` int DEFAULT NULL,
  `sim_type_id` int DEFAULT NULL,
  `ORDER_NUMBER` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SERVICE_GRANT` tinyint DEFAULT '0' COMMENT '0 is No and 1 is Yes',
  `IMEI_LOCK` tinyint DEFAULT '0' COMMENT '0 is No and 1 is Yes',
  `OLD_PROFILE_STATE` varchar(56) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CURRENT_PROFILE_STATE` varchar(56) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `custom_param_1` varchar(96) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `custom_param_2` varchar(96) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `custom_param_3` varchar(96) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `custom_param_4` varchar(96) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `custom_param_5` varchar(96) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `BULK_SERVICE_NAME` json DEFAULT NULL,
  `FVS_DATA` json DEFAULT NULL COMMENT 'To Store FVS JSON DATA',
  `sim_category` varchar(56) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'stores value sim_category(830,831,05X)',
  `lock_by_user` varchar(256) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `imei_lock_setup_date` datetime DEFAULT NULL,
  `imei_lock_disable_date` datetime DEFAULT NULL,
  `Error_Message` text COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB ;



DROP TABLE IF EXISTS `migration_assets_extended`;
CREATE TABLE `migration_assets_extended` (
  `ID` bigint DEFAULT NULL,
  `CREATE_DATE` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `voice_template` int DEFAULT NULL,
  `sms_template` int DEFAULT NULL,
  `data_template` int DEFAULT NULL,
  `sim_type_id` int DEFAULT NULL,
  `ORDER_NUMBER` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SERVICE_GRANT` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '0 is No and 1 is Yes',
  `IMEI_LOCK` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '0 is No and 1 is Yes',
  `OLD_PROFILE_STATE` varchar(56) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `CURRENT_PROFILE_STATE` varchar(56) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `custom_param_1` varchar(96) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `custom_param_2` varchar(96) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `custom_param_3` varchar(96) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `custom_param_4` varchar(96) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `custom_param_5` varchar(96) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `BULK_SERVICE_NAME` json DEFAULT NULL,
  `FVS_DATA` json DEFAULT NULL COMMENT 'To Store FVS JSON DATA',
  `sim_category` varchar(56) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'stores value sim_category(830,831,05X)',
  `lock_by_user` varchar(256) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `imei_lock_setup_date` datetime DEFAULT NULL,
  `imei_lock_disable_date` datetime DEFAULT NULL
) ENGINE=InnoDB ;


CREATE TABLE IF NOT EXISTS `migration_tracking_history` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `database_name` varchar(255) DEFAULT NULL,
  `query_print` longtext,
  `create_date` datetime DEFAULT NULL,
  `message_status` longtext,
  `is_completed` tinyint DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
