DROP PROCEDURE IF EXISTS migration_sim_bulk_insert;
DELIMITER //
CREATE PROCEDURE `migration_sim_bulk_insert`()
BEGIN

/*
-- *************************************************************************
-- Procedure: migration_sim_bulk_insert_test
-- Author: manish saini
-- Date: 2024-02-22
-- Description: Procedure for automated sim_bulk_insert
-- *************************************************************************

selectg max(id) from assets_extended;  105=a
selectg max(ASSETS_EXTENDED_ID) from assets; 100=b
selectg max(id) from assets; 200=c
assets_extended id= 106
assets id =201
IP: 192.168.1.122
db name : stc_dev_p2

IFNULL(CREATE_DATE,NOW())
IFNULL(ACTIVATION_DATE,NOW())
IFNULL(BILLING_CYCLE,1)
MNO_ACCOUNTID= (SELECT ID FROM accounts WHERE TYPE=3 AND NAME='KSA_OPCO' AND DELETED=0)
IFNULL(STATE_MODIFIED_DATE,NOW())
IFNULL(DEVICE_PLAN_DATE,NOW())

NULL =ICCID = F
NULL =IMSI = F
NULL =MSISDN = F
NULL =STATE = F
NULL =COUNTRIES_ID=F
NULL =DEVICE_PLAN_ID = F
NULL= ENT_ACCOUNTID=F

select a.id,a.plan_name,c.NOTIFICATION_UUID from device_rate_plan as a inner join device_plan_to_service_apn_mapping as b on b.DEVICE_PLAN_ID_ID=a.ID inner join accounts as c on a.account_id=c.id where a.status=0 order
by a.id desc limit 10;


*/

DECLARE EXIT handler FOR SQLEXCEPTION
BEGIN

GET DIAGNOSTICS CONDITION 1
@p1 = RETURNED_SQLSTATE, @p2 = MESSAGE_TEXT;
SELECT DATABASE(), CONCAT(@p1 , @p2) INTO @database, @MESSAGE_TEXT;

SET @error_history = CONCAT("INSERT INTO migration_tracking_history(database_name,query_print,create_date, message_status) SELECT '",@database,"',0, now() ,'",@MESSAGE_TEXT,"';");

SELECT COUNT(1) INTO @before_excution FROM assets;
SELECT CONCAT('before_excution: ',IFNULL(@before_excution,0)) as before_excution,
CONCAT('after_execution: ',IFNULL(@before_excution,0)) as after_execution,
CONCAT('success_count: ',0) as success_count,
CONCAT('failed_count: ',0) as failed_count,
IFNULL(@MESSAGE_TEXT,'') as Remarks;

PREPARE stmt_1 FROM @error_history;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;
  ROLLBACK; 
END ;

SET @cntsimtype=NULL;
SET @cntsimcategory=NULL;
SET @cnticcid=NULL;
SET @cntimsi=NULL;
SET @cntmsisdn=NULL;
SET @cntstate=NULL;
SET @cntcountriesid=NULL;
SET @cntdeviceplanid=NULL;
SET @cntentaccountid=NULL;
SET @migrationassetsextended=NULL;
SET @migrationassets=NULL;
SET @before_excution=0;
SET @after_execution=0;
SET @success_count=0;
SET @failed_count_ex=0;
SET @failed_count=0;
SET @MESSAGE_TEXT='';
SET @delete_history='';
SET @Update_history='';
SET @insert_assets_extended='';
SET @insert_assets='';
SET @success_history='';

SET @delete_history = CONCAT("DELETE FROM migration_tracking_history WHERE  create_date < DATE_SUB(DATE(NOW()) ,INTERVAL 15 DAY);");
-- SELECT @delete_history;
prepare stmt_1 from @delete_history;
execute stmt_1;
deallocate prepare stmt_1;



SET @Update_history = CONCAT("Update migration_tracking_history set is_completed=0;");
-- SELECT @Update_history;

prepare stmt_1 from @Update_history;
execute stmt_1;
deallocate prepare stmt_1;

-- error insert in error history TABLE

TRUNCATE TABLE migration_assets_error_history;
TRUNCATE TABLE migration_assets_extended_error_history;

-- CREATE TABLE IF NOT EXISTS migration_assets_220224 SELECT * from migration_assets;
-- CREATE TABLE IF NOT EXISTS migration_assets_extended_220224 SELECT * from migration_assets_extended;

DROP TEMPORARY TABLE IF EXISTS `temp_assets_imsi`;
CREATE temporary TABLE `temp_assets_imsi` (
   `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `imsi` varchar(128) DEFAULT NULL) ;
   
DROP TEMPORARY TABLE IF EXISTS `temp_assets_iccid`;
CREATE temporary TABLE `temp_assets_iccid` (
   `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `iccid` varchar(128) DEFAULT NULL) ;
   
DROP TEMPORARY TABLE IF EXISTS `temp_assets_msisdn`;
CREATE temporary TABLE `temp_assets_msisdn` (
   `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `msisdn` varchar(128) DEFAULT NULL);

INSERT INTO temp_assets_imsi(imsi) SELECT DISTINCT a.imsi 
FROM migration_assets AS a INNER JOIN assets AS b ON TRIM(a.imsi)=b.imsi;

INSERT INTO temp_assets_iccid(iccid)
SELECT DISTINCT a.iccid 
FROM migration_assets AS a INNER JOIN assets AS b ON TRIM(a.iccid)=b.iccid;

INSERT INTO temp_assets_msisdn(msisdn)
SELECT DISTINCT a.msisdn 
from migration_assets AS a INNER JOIN assets AS b ON TRIM(a.msisdn)=b.msisdn;


INSERT INTO migration_assets_extended_error_history (`CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`,`Error_Message`)
SELECT `CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`,'invalid sim_type_id value' from migration_assets_extended WHERE ((sim_type_id NOT in (3,4) OR sim_type_id IS NULL));

-- select 'section 1';

INSERT INTO migration_assets_extended_error_history(`CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`,`Error_Message`)
SELECT `CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`,'invalid sim_category value' from migration_assets_extended WHERE ((sim_category NOT in ('831','830','05X') OR sim_category IS NULL));

-- select 'section 2';

DROP TEMPORARY TABLE IF EXISTS `migration_assets_extended_error_history_2040224`;
CREATE temporary TABLE migration_assets_extended_error_history_2040224 SELECT DISTINCT `CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`,GROUP_CONCAT(Error_Message) as Error_Message FROM migration_assets_extended_error_history GROUP BY `CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`;

-- select 'section 3';

TRUNCATE TABLE migration_assets_extended_error_history;
INSERT INTO migration_assets_extended_error_history(`CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`,Error_Message) SELECT DISTINCT `CREATE_DATE`,`voice_template`,`sms_template`,`data_template`,`sim_type_id`,`ORDER_NUMBER`,`SERVICE_GRANT`,`IMEI_LOCK`,`OLD_PROFILE_STATE`,`CURRENT_PROFILE_STATE`,`custom_param_1`,`custom_param_2`,`custom_param_3`,`custom_param_4`,`custom_param_5`,`BULK_SERVICE_NAME`,`FVS_DATA`,`sim_category`,`lock_by_user`,`imei_lock_setup_date`,`imei_lock_disable_date`,Error_Message FROM migration_assets_extended_error_history_2040224;
TRUNCATE TABLE migration_assets_extended_error_history_2040224;


-- select 'section 4';
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`) 
SELECT `CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,'invalid ICCID value' FROM migration_assets WHERE (ICCID IS NULL OR ICCID='');

-- select 'section 5';
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`) 
SELECT `CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,'invalid imsi value' FROM migration_assets WHERE (IMSI IS NULL OR IMSI='');

-- select 'section 6';
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`) 
SELECT `CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,'invalid msisdn value' FROM migration_assets WHERE (MSISDN IS NULL OR MSISDN='');

-- select 'section 7';
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`) 
SELECT `CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,'invalid state value' FROM migration_assets WHERE (STATE IS NULL OR STATE='');

-- select 'section 8';
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`) 
SELECT `CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,'invalid countries value' FROM migration_assets WHERE (COUNTRIES_ID IS NULL OR COUNTRIES_ID='');

-- select 'section 9';
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`) 
SELECT `CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,'invalid device plan value' FROM migration_assets WHERE (DEVICE_PLAN_ID IS NULL OR DEVICE_PLAN_ID='');

-- select 'section 10';
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`) 
SELECT `CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,'invalid account number value' FROM migration_assets WHERE (ENT_ACCOUNTID IS NULL OR ENT_ACCOUNTID='');

-- select 'section 11';
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`) 
SELECT DISTINCT a.`CREATE_DATE`,a.`ACTIVATION_DATE`,a.`APN`,a.`DATA_USAGE_LIMIT`,a.`DEVICE_ID`,a.`DEVICE_IP_ADDRESS`,a.`DYNAMIC_IMSI`,a.`DONOR_IMSI`,a.`ICCID`,a.`IMEI`,a.`IMSI`,a.`IN_SESSION`,a.`MODEM_ID`,a.`MSISDN`,a.`SESSION_START_TIME`,a.`SMS_USAGE_LIMIT`,a.`STATE`,a.`STATUS`,a.`VOICE_USAGE_LIMIT`,a.`SUBSCRIBER_NAME`,a.`SUBSCRIBER_LAST_NAME`,a.`SUBSCRIBER_GENDER`,a.`SUBSCRIBER_DOB`,a.`ALTERNATE_CONTACT_NUMBER`,a.`SUBSCRIBER_EMAIL`,a.`SUBSCRIBER_ADDRESS`,a.`CUSTOM_PARAM_1`,a.`CUSTOM_PARAM_2`,a.`CUSTOM_PARAM_3`,a.`CUSTOM_PARAM_4`,a.`CUSTOM_PARAM_5`,a.`SERVICE_PLAN_ID`,a.`LOCATION_COVERAGE_ID`,a.`NEXT_LOCATION_COVERAGE_ID`,a.`BILLING_CYCLE`,a.`RATE_PLAN_ID`,a.`NEXT_RATE_PLAN_ID`,a.`MNO_ACCOUNTID`,a.`ENT_ACCOUNTID`,a.`TOTAL_DATA_USAGE`,a.`TOTAL_DATA_DOWNLOAD`,a.`TOTAL_DATA_UPLOAD`,a.`DATA_USAGE_THRESHOLD`,a.`IP_ADDRESS`,a.`LAST_KNOWN_LOCATION`,a.`LAST_KNOWN_NETWORK`,a.`STATE_MODIFIED_DATE`,a.`USAGES_NOTIFICATION`,a.`BSS_ID`,a.`GOUP_ID`,a.`LOCK_REFERENCE`,a.`SIM_POOL_ID`,a.`WHOLESALE_PLAN_ID`,a.`PROFILE_STATE`,a.`EUICC_ID`,a.`OPERATIONAL_PROFILE_DATA_PLAN`,a.`BOOTSTRAP_PROFILE`,a.`CURRENT_IMEI`,a.`ASSETS_EXTENDED_ID`,a.`DEVICE_PLAN_ID`,a.`DEVICE_PLAN_DATE`,a.`COUNTRIES_ID`,a.`DONOR_ICCID`,'invalid countries value' FROM migration_assets AS a LEFT JOIN accounts AS b ON TRIM(a.ENT_ACCOUNTID)=b.NOTIFICATION_UUID LEFT JOIN countries AS c ON TRIM(a.COUNTRIES_ID)=c.NAME LEFT JOIN device_rate_plan AS d ON TRIM(a.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID WHERE (c.NAME IS NULL OR c.NAME='');

-- select 'section 12';
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`) 
SELECT DISTINCT a.`CREATE_DATE`,a.`ACTIVATION_DATE`,a.`APN`,a.`DATA_USAGE_LIMIT`,a.`DEVICE_ID`,a.`DEVICE_IP_ADDRESS`,a.`DYNAMIC_IMSI`,a.`DONOR_IMSI`,a.`ICCID`,a.`IMEI`,a.`IMSI`,a.`IN_SESSION`,a.`MODEM_ID`,a.`MSISDN`,a.`SESSION_START_TIME`,a.`SMS_USAGE_LIMIT`,a.`STATE`,a.`STATUS`,a.`VOICE_USAGE_LIMIT`,a.`SUBSCRIBER_NAME`,a.`SUBSCRIBER_LAST_NAME`,a.`SUBSCRIBER_GENDER`,a.`SUBSCRIBER_DOB`,a.`ALTERNATE_CONTACT_NUMBER`,a.`SUBSCRIBER_EMAIL`,a.`SUBSCRIBER_ADDRESS`,a.`CUSTOM_PARAM_1`,a.`CUSTOM_PARAM_2`,a.`CUSTOM_PARAM_3`,a.`CUSTOM_PARAM_4`,a.`CUSTOM_PARAM_5`,a.`SERVICE_PLAN_ID`,a.`LOCATION_COVERAGE_ID`,a.`NEXT_LOCATION_COVERAGE_ID`,a.`BILLING_CYCLE`,a.`RATE_PLAN_ID`,a.`NEXT_RATE_PLAN_ID`,a.`MNO_ACCOUNTID`,a.`ENT_ACCOUNTID`,a.`TOTAL_DATA_USAGE`,a.`TOTAL_DATA_DOWNLOAD`,a.`TOTAL_DATA_UPLOAD`,a.`DATA_USAGE_THRESHOLD`,a.`IP_ADDRESS`,a.`LAST_KNOWN_LOCATION`,a.`LAST_KNOWN_NETWORK`,a.`STATE_MODIFIED_DATE`,a.`USAGES_NOTIFICATION`,a.`BSS_ID`,a.`GOUP_ID`,a.`LOCK_REFERENCE`,a.`SIM_POOL_ID`,a.`WHOLESALE_PLAN_ID`,a.`PROFILE_STATE`,a.`EUICC_ID`,a.`OPERATIONAL_PROFILE_DATA_PLAN`,a.`BOOTSTRAP_PROFILE`,a.`CURRENT_IMEI`,a.`ASSETS_EXTENDED_ID`,a.`DEVICE_PLAN_ID`,a.`DEVICE_PLAN_DATE`,a.`COUNTRIES_ID`,a.`DONOR_ICCID`,'invalid device plan and account id is not mapping to device plan' FROM migration_assets AS a LEFT JOIN accounts AS b ON TRIM(a.ENT_ACCOUNTID)=b.NOTIFICATION_UUID LEFT JOIN countries AS c ON TRIM(a.COUNTRIES_ID)=c.NAME LEFT JOIN device_rate_plan AS d ON TRIM(a.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID WHERE (d.PLAN_NAME IS NULL OR d.PLAN_NAME='');

-- select 'section 13';
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`) 
SELECT DISTINCT a.`CREATE_DATE`,a.`ACTIVATION_DATE`,a.`APN`,a.`DATA_USAGE_LIMIT`,a.`DEVICE_ID`,a.`DEVICE_IP_ADDRESS`,a.`DYNAMIC_IMSI`,a.`DONOR_IMSI`,a.`ICCID`,a.`IMEI`,a.`IMSI`,a.`IN_SESSION`,a.`MODEM_ID`,a.`MSISDN`,a.`SESSION_START_TIME`,a.`SMS_USAGE_LIMIT`,a.`STATE`,a.`STATUS`,a.`VOICE_USAGE_LIMIT`,a.`SUBSCRIBER_NAME`,a.`SUBSCRIBER_LAST_NAME`,a.`SUBSCRIBER_GENDER`,a.`SUBSCRIBER_DOB`,a.`ALTERNATE_CONTACT_NUMBER`,a.`SUBSCRIBER_EMAIL`,a.`SUBSCRIBER_ADDRESS`,a.`CUSTOM_PARAM_1`,a.`CUSTOM_PARAM_2`,a.`CUSTOM_PARAM_3`,a.`CUSTOM_PARAM_4`,a.`CUSTOM_PARAM_5`,a.`SERVICE_PLAN_ID`,a.`LOCATION_COVERAGE_ID`,a.`NEXT_LOCATION_COVERAGE_ID`,a.`BILLING_CYCLE`,a.`RATE_PLAN_ID`,a.`NEXT_RATE_PLAN_ID`,a.`MNO_ACCOUNTID`,a.`ENT_ACCOUNTID`,a.`TOTAL_DATA_USAGE`,a.`TOTAL_DATA_DOWNLOAD`,a.`TOTAL_DATA_UPLOAD`,a.`DATA_USAGE_THRESHOLD`,a.`IP_ADDRESS`,a.`LAST_KNOWN_LOCATION`,a.`LAST_KNOWN_NETWORK`,a.`STATE_MODIFIED_DATE`,a.`USAGES_NOTIFICATION`,a.`BSS_ID`,a.`GOUP_ID`,a.`LOCK_REFERENCE`,a.`SIM_POOL_ID`,a.`WHOLESALE_PLAN_ID`,a.`PROFILE_STATE`,a.`EUICC_ID`,a.`OPERATIONAL_PROFILE_DATA_PLAN`,a.`BOOTSTRAP_PROFILE`,a.`CURRENT_IMEI`,a.`ASSETS_EXTENDED_ID`,a.`DEVICE_PLAN_ID`,a.`DEVICE_PLAN_DATE`,a.`COUNTRIES_ID`,a.`DONOR_ICCID`,'invalid account value' FROM migration_assets AS a LEFT JOIN accounts AS b ON TRIM(a.ENT_ACCOUNTID)=b.NOTIFICATION_UUID LEFT JOIN countries AS c ON TRIM(a.COUNTRIES_ID)=c.NAME LEFT JOIN device_rate_plan AS d ON TRIM(a.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID WHERE (b.NAME IS NULL OR b.NAME='');

-- select 'section 14';
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,`Error_Message`) 
SELECT `CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,'Existing Duplicate records failed'
from migration_assets assets WHERE (assets.IMSI IN (SELECT DISTINCT imsi FROM temp_assets_imsi) OR assets.ICCID IN (SELECT DISTINCT iccid FROM temp_assets_iccid) OR assets.MSISDN IN (SELECT DISTINCT msisdn FROM temp_assets_msisdn));


-- select 'section 15';
DROP TEMPORARY TABLE IF EXISTS `migration_assets_error_history_2040224`;
CREATE temporary TABLE migration_assets_error_history_2040224 SELECT DISTINCT `CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,GROUP_CONCAT(Error_Message) as error_message FROM migration_assets_error_history GROUP BY `CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`;

-- select 'section 16';
TRUNCATE TABLE migration_assets_error_history;
INSERT INTO migration_assets_error_history(`CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,Error_Message) SELECT DISTINCT `CREATE_DATE`,`ACTIVATION_DATE`,`APN`,`DATA_USAGE_LIMIT`,`DEVICE_ID`,`DEVICE_IP_ADDRESS`,`DYNAMIC_IMSI`,`DONOR_IMSI`,`ICCID`,`IMEI`,`IMSI`,`IN_SESSION`,`MODEM_ID`,`MSISDN`,`SESSION_START_TIME`,`SMS_USAGE_LIMIT`,`STATE`,`STATUS`,`VOICE_USAGE_LIMIT`,`SUBSCRIBER_NAME`,`SUBSCRIBER_LAST_NAME`,`SUBSCRIBER_GENDER`,`SUBSCRIBER_DOB`,`ALTERNATE_CONTACT_NUMBER`,`SUBSCRIBER_EMAIL`,`SUBSCRIBER_ADDRESS`,`CUSTOM_PARAM_1`,`CUSTOM_PARAM_2`,`CUSTOM_PARAM_3`,`CUSTOM_PARAM_4`,`CUSTOM_PARAM_5`,`SERVICE_PLAN_ID`,`LOCATION_COVERAGE_ID`,`NEXT_LOCATION_COVERAGE_ID`,`BILLING_CYCLE`,`RATE_PLAN_ID`,`NEXT_RATE_PLAN_ID`,`MNO_ACCOUNTID`,`ENT_ACCOUNTID`,`TOTAL_DATA_USAGE`,`TOTAL_DATA_DOWNLOAD`,`TOTAL_DATA_UPLOAD`,`DATA_USAGE_THRESHOLD`,`IP_ADDRESS`,`LAST_KNOWN_LOCATION`,`LAST_KNOWN_NETWORK`,`STATE_MODIFIED_DATE`,`USAGES_NOTIFICATION`,`BSS_ID`,`GOUP_ID`,`LOCK_REFERENCE`,`SIM_POOL_ID`,`WHOLESALE_PLAN_ID`,`PROFILE_STATE`,`EUICC_ID`,`OPERATIONAL_PROFILE_DATA_PLAN`,`BOOTSTRAP_PROFILE`,`CURRENT_IMEI`,`ASSETS_EXTENDED_ID`,`DEVICE_PLAN_ID`,`DEVICE_PLAN_DATE`,`COUNTRIES_ID`,`DONOR_ICCID`,Error_Message FROM migration_assets_error_history_2040224;
TRUNCATE TABLE migration_assets_error_history_2040224;

-- select 'section 16';

--  check validation

-- SELECT count(1) into @exitsmigrationassets from migration_assets assets WHERE (assets.IMSI IN (SELECT DISTINCT IMSI FROM ASSETS) OR assets.ICCID IN (SELECT DISTINCT ICCID FROM ASSETS) OR assets.MSISDN IN (SELECT DISTINCT MSISDN FROM ASSETS));

-- SELECT count(1) into @idassetsless from migration_assets WHERE ID IN (SELECT ID FROM assets);


SELECT count(1) into @migrationassets from migration_assets;
SELECT count(1) into @migrationassetsextended from migration_assets_extended;

SELECT COUNT(1) INTO @before_excution FROM assets;

-- select 'section 18';
-- SELECT @cntsimtype,@cntsimcategory,@cnticcid,@cntimsi,@cntmsisdn,@cntstate,@cntcountriesid,@cntdeviceplanid,@cntentaccountid,@migrationassetsextended,@migrationassets,@cntcountriesname,@cntdeviceplanname,@cntentaccountname;


IF(@migrationassetsextended>0 AND @migrationassets>0)
THEN


SET FOREIGN_KEY_CHECKS=0;

START TRANSACTION;

SET @insert_assets_extended = CONCAT("INSERT INTO assets_extended(ID, `CREATE_DATE`, `voice_template`, `sms_template`, `data_template`, `sim_type_id`, `ORDER_NUMBER`, `SERVICE_GRANT`, `IMEI_LOCK`, `OLD_PROFILE_STATE`, `CURRENT_PROFILE_STATE`, `custom_param_1`, `custom_param_2`, `custom_param_3`, `custom_param_4`, `custom_param_5`, `BULK_SERVICE_NAME`, `FVS_DATA`, `sim_category`) SELECT ID,`CREATE_DATE`, `voice_template`, `sms_template`, `data_template`, `sim_type_id`, `ORDER_NUMBER`, `SERVICE_GRANT`, `IMEI_LOCK`, `OLD_PROFILE_STATE`, `CURRENT_PROFILE_STATE`, `custom_param_1`, `custom_param_2`, `custom_param_3`, `custom_param_4`, `custom_param_5`, `BULK_SERVICE_NAME`, `FVS_DATA`, `sim_category` FROM migration_assets_extended WHERE ID NOT IN (SELECT ID FROM assets_extended) AND ((sim_type_id in (3,4) OR sim_type_id IS NOT NULL)) AND ((sim_category in ('831','830','05X') OR sim_category IS NOT NULL));");
 
 
-- SELECT @insert_assets_extended;

PREPARE stmt_1 FROM @insert_assets_extended;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

COMMIT;

SET @insert_assets = CONCAT("INSERT INTO assets(ID,`CREATE_DATE`, `ACTIVATION_DATE`, `APN`, `DATA_USAGE_LIMIT`, `DEVICE_ID`, `DEVICE_IP_ADDRESS`, `DYNAMIC_IMSI`, `DONOR_IMSI`, `ICCID`, `IMEI`, `IMSI`, `IN_SESSION`, `MODEM_ID`, `MSISDN`, `SESSION_START_TIME`, `SMS_USAGE_LIMIT`, `STATE`, `STATUS`, `VOICE_USAGE_LIMIT`, `SUBSCRIBER_NAME`, `SUBSCRIBER_LAST_NAME`, `SUBSCRIBER_GENDER`, `SUBSCRIBER_DOB`, `ALTERNATE_CONTACT_NUMBER`, `SUBSCRIBER_EMAIL`, `SUBSCRIBER_ADDRESS`, `CUSTOM_PARAM_1`, `CUSTOM_PARAM_2`, `CUSTOM_PARAM_3`, `CUSTOM_PARAM_4`, `CUSTOM_PARAM_5`, `SERVICE_PLAN_ID`, `LOCATION_COVERAGE_ID`, `NEXT_LOCATION_COVERAGE_ID`, `BILLING_CYCLE`, `RATE_PLAN_ID`, `NEXT_RATE_PLAN_ID`, `MNO_ACCOUNTID`, `ENT_ACCOUNTID`, `TOTAL_DATA_USAGE`, `TOTAL_DATA_DOWNLOAD`, `TOTAL_DATA_UPLOAD`, `DATA_USAGE_THRESHOLD`, `IP_ADDRESS`, `LAST_KNOWN_LOCATION`, `LAST_KNOWN_NETWORK`, `STATE_MODIFIED_DATE`, `USAGES_NOTIFICATION`, `BSS_ID`, `GOUP_ID`, `LOCK_REFERENCE`, `SIM_POOL_ID`, `WHOLESALE_PLAN_ID`, `PROFILE_STATE`, `EUICC_ID`, `OPERATIONAL_PROFILE_DATA_PLAN`, `BOOTSTRAP_PROFILE`, `CURRENT_IMEI`, `ASSETS_EXTENDED_ID`, `DEVICE_PLAN_ID`, `DEVICE_PLAN_DATE`, `COUNTRIES_ID`, `DONOR_ICCID`) 
SELECT DISTINCT assets.ID, IFNULL(`assets`.`CREATE_DATE`,NOW()), `assets`.`ACTIVATION_DATE`, `assets`.`APN`, `assets`.`DATA_USAGE_LIMIT`, `assets`.`DEVICE_ID`, `assets`.`DEVICE_IP_ADDRESS`, `assets`.`DYNAMIC_IMSI`, `assets`.`DONOR_IMSI`, `assets`.`ICCID`, `assets`.`IMEI`, `assets`.`IMSI`, IFNULL(`assets`.`IN_SESSION`,0), `assets`.`MODEM_ID`, `assets`.`MSISDN`, `assets`.`SESSION_START_TIME`, `assets`.`SMS_USAGE_LIMIT`, IFNULL(`assets`.`STATE`,'Activated'), IFNULL(`assets`.`STATUS`,'Activated'), `assets`.`VOICE_USAGE_LIMIT`, `assets`.`SUBSCRIBER_NAME`, `assets`.`SUBSCRIBER_LAST_NAME`, IFNULL(`assets`.`SUBSCRIBER_GENDER`,0), `assets`.`SUBSCRIBER_DOB`, `assets`.`ALTERNATE_CONTACT_NUMBER`, `assets`.`SUBSCRIBER_EMAIL`, `assets`.`SUBSCRIBER_ADDRESS`, `assets`.`CUSTOM_PARAM_1`, `assets`.`CUSTOM_PARAM_2`, `assets`.`CUSTOM_PARAM_3`, `assets`.`CUSTOM_PARAM_4`, `assets`.`CUSTOM_PARAM_5`, e.SERVICE_PLAN_ID, `assets`.`LOCATION_COVERAGE_ID`, IFNULL(`assets`.`NEXT_LOCATION_COVERAGE_ID`,0), IFNULL(`assets`.`BILLING_CYCLE`,1), `assets`.`RATE_PLAN_ID`, `assets`.`NEXT_RATE_PLAN_ID`, (SELECT ID FROM accounts WHERE TYPE=3 AND NAME='KSA_OPCO' AND DELETED=0), `b`.`id`, IFNULL(`assets`.`TOTAL_DATA_USAGE`,0), IFNULL(`assets`.`TOTAL_DATA_DOWNLOAD`,0), IFNULL(`assets`.`TOTAL_DATA_UPLOAD`,0), IFNULL(`assets`.`DATA_USAGE_THRESHOLD`,0), `assets`.`IP_ADDRESS`, `assets`.`LAST_KNOWN_LOCATION`, `assets`.`LAST_KNOWN_NETWORK`, IFNULL(`assets`.`STATE_MODIFIED_DATE`,NOW()), IFNULL(`assets`.`USAGES_NOTIFICATION`,0), `assets`.`BSS_ID`, `assets`.`GOUP_ID`, `assets`.`LOCK_REFERENCE`, `assets`.`SIM_POOL_ID`, `assets`.`WHOLESALE_PLAN_ID`, `assets`.`PROFILE_STATE`, `assets`.`EUICC_ID`, `assets`.`OPERATIONAL_PROFILE_DATA_PLAN`, `assets`.`BOOTSTRAP_PROFILE`, `assets`.`CURRENT_IMEI`, `assets`.`ASSETS_EXTENDED_ID`, `d`.`id`, IFNULL(`assets`.`DEVICE_PLAN_DATE`,NOW()), `c`.`ID`, `assets`.`DONOR_ICCID` FROM migration_assets AS assets LEFT JOIN accounts AS b ON TRIM(assets.ENT_ACCOUNTID)=b.NOTIFICATION_UUID AND b.DELETED=0 INNER JOIN countries AS c ON TRIM(assets.COUNTRIES_ID)=c.NAME LEFT JOIN device_rate_plan AS d ON TRIM(assets.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID AND d.DELETED=0 LEFT JOIN device_service_plan_mapping as e on e.DEVICE_PLAN_ID=d.id WHERE ((c.NAME IS NOT NULL OR c.NAME<>'') OR (assets.COUNTRIES_ID IS NOT NULL OR assets.COUNTRIES_ID<>'') OR (assets.MSISDN IS NOT NULL OR assets.MSISDN<>'') OR (assets.IMSI IS NOT NULL OR assets.IMSI<>'') OR (assets.ICCID IS NOT NULL OR assets.ICCID<>'') OR (b.NAME IS NOT NULL OR b.NAME<>'')) AND assets.ID NOT IN (SELECT ID from migration_assets assets WHERE (assets.IMSI IN (SELECT DISTINCT imsi FROM temp_assets_imsi) OR assets.ICCID IN (SELECT DISTINCT iccid FROM temp_assets_iccid) OR assets.MSISDN IN (SELECT DISTINCT msisdn FROM temp_assets_msisdn)));");
COMMIT;
-- select @insert_assets;
PREPARE stmt_1 FROM @insert_assets;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SET FOREIGN_KEY_CHECKS=1;


SET @delete_assets_extended = CONCAT("DELETE FROM assets_extended WHERE ID NOT IN (SELECT ASSETS_EXTENDED_ID FROM assets);");
-- select @delete_assets_extended;
PREPARE stmt_1 FROM @delete_assets_extended;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SELECT count(1) INTO @success_count from assets WHERE ID IN (SELECT ID FROM migration_assets);

ELSEIF(@migrationassets=0 AND @migrationassetsextended=0) THEN

SELECT 'No Records Found in migration_assets and migration_assets_extended table' INTO @MESSAGE_TEXT;

SET @error_history = CONCAT("INSERT INTO migration_tracking_history(database_name,query_print,create_date, message_status,is_completed) SELECT 
DATABASE(),'failure',now(),'",@MESSAGE_TEXT,"',1;");
-- select @error_history;
PREPARE stmt_1 FROM @error_history;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;
END IF;
COMMIT;
SELECT count(1) INTO @failed_count from migration_assets WHERE ID NOT IN (SELECT ID FROM assets);
SELECT COUNT(1) INTO @after_execution FROM assets;

/*
DELETE n1 FROM service_apn_account_mapping n1, service_apn_account_mapping n2 WHERE n1.id < n2.id AND n1.ACCOUNT_ID = n2.ACCOUNT_ID AND n1.APN_ID = n2.APN_ID ;

DELETE n1 FROM apn_ip_mapping n1, apn_ip_mapping n2 WHERE n1.id < n2.id AND n1.IP_ID = n2.IP_ID AND n1.APN_ID = n2.APN_ID AND n1.ASSETS_ID = n2.ASSETS_ID;

DELETE n1 FROM assets_apn_allocation n1, assets_apn_allocation n2 WHERE n1.id < n2.id AND n1.ASSETS_ID = n2.ASSETS_ID AND n1.APN_ID = n2.APN_ID ;

*/
IF(@after_execution>@before_excution) THEN
-- mapping apn to assets
START TRANSACTION;


INSERT INTO service_apn_account_mapping(ACCOUNT_ID,APN_ID,CREATE_DATE)
SELECT distinct assets.ENT_ACCOUNTID, f.APN_ID,NOW() FROM migration_assets assets INNER JOIN accounts AS b ON TRIM(assets.ENT_ACCOUNTID)=b.NOTIFICATION_UUID AND b.DELETED=0 INNER JOIN device_rate_plan AS d ON TRIM(assets.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID AND d.DELETED=0 INNER JOIN device_plan_to_service_apn_mapping as e on e.DEVICE_PLAN_ID_ID=d.ID INNER JOIN Service_Apn_ip as f on assets.IP_ADDRESS=f.APN_IP WHERE (assets.ENT_ACCOUNTID NOT IN (SELECT ACCOUNT_ID FROM service_apn_account_mapping) AND f.APN_ID NOT IN (SELECT APN_ID FROM service_apn_account_mapping));

INSERT INTO apn_ip_mapping(APN_ID,IP_ID,CREATE_DATE,ASSETS_ID)
SELECT distinct f.APN_ID,f.ID,NOW(),assets.ID FROM migration_assets assets INNER JOIN accounts AS b ON TRIM(assets.ENT_ACCOUNTID)=b.NOTIFICATION_UUID AND b.DELETED=0 INNER JOIN device_rate_plan AS d ON TRIM(assets.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID AND d.DELETED=0 INNER JOIN device_plan_to_service_apn_mapping as e on e.DEVICE_PLAN_ID_ID=d.ID INNER JOIN Service_Apn_ip as f on assets.IP_ADDRESS=f.APN_IP WHERE 
assets.ID NOT IN (SELECT DISTINCT ASSETS_ID FROM apn_ip_mapping);

INSERT INTO assets_apn_allocation(ASSETS_ID,APN_ID,CREATE_DATE)
SELECT distinct assets.ID,f.APN_ID,NOW() FROM migration_assets assets INNER JOIN accounts AS b ON TRIM(assets.ENT_ACCOUNTID)=b.NOTIFICATION_UUID AND b.DELETED=0 INNER JOIN device_rate_plan AS d ON TRIM(assets.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID AND d.DELETED=0 INNER JOIN device_plan_to_service_apn_mapping as e on e.DEVICE_PLAN_ID_ID=d.ID  INNER JOIN Service_Apn_ip as f on assets.IP_ADDRESS=f.APN_IP WHERE assets.ID NOT IN (SELECT DISTINCT ASSETS_ID FROM assets_apn_allocation);
-- update query "in_use" map 


SET @getsapndet_list = CONCAT("SELECT IFNULL(GROUP_CONCAT(distinct f.APN_ID),0) INTO @sapndet_list FROM migration_assets assets INNER JOIN accounts AS b ON TRIM(assets.ENT_ACCOUNTID)=b.NOTIFICATION_UUID AND b.DELETED=0 INNER JOIN device_rate_plan AS d ON TRIM(assets.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID AND d.DELETED=0 INNER JOIN device_plan_to_service_apn_mapping as e on e.DEVICE_PLAN_ID_ID=d.ID INNER JOIN Service_Apn_ip as f on assets.IP_ADDRESS=f.APN_IP");
-- select @getsapndet_list;
PREPARE stmt_1 FROM @getsapndet_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SET @updsapndet_list = CONCAT("UPDATE service_apn_details as sad SET sad.status='IN_USE' WHERE sad.ID IN (",@sapndet_list,")  AND (sad.status='NOT_IN_USE' OR sad.status IS NULL);");
-- select @getsapndet_list;
PREPARE stmt_1 FROM @updsapndet_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SET @getspi_list = CONCAT("SELECT IFNULL(GROUP_CONCAT(distinct f.ID),0) INTO @spi_list FROM  migration_assets assets INNER JOIN accounts AS b ON TRIM(assets.ENT_ACCOUNTID)=b.NOTIFICATION_UUID AND b.DELETED=0 INNER JOIN device_rate_plan AS d ON TRIM(assets.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID AND d.DELETED=0 INNER JOIN device_plan_to_service_apn_mapping as e on e.DEVICE_PLAN_ID_ID=d.ID INNER JOIN Service_Apn_ip as f on assets.IP_ADDRESS=f.APN_IP");
-- select @getsapndet_list;
PREPARE stmt_1 FROM @getspi_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SET @updgetspi_list = CONCAT("UPDATE Service_Apn_ip as sp SET sp.isUse=1 WHERE sp.ID IN (",@spi_list,")  AND (sp.isUse=0 OR sp.isUse IS NULL)");
-- select @getsapndet_list;
PREPARE stmt_1 FROM @updgetspi_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SET @getdp_list = CONCAT("SELECT IFNULL(GROUP_CONCAT(distinct d.ID),0) INTO @dp_list FROM  migration_assets assets INNER JOIN accounts AS b ON TRIM(assets.ENT_ACCOUNTID)=b.NOTIFICATION_UUID AND b.DELETED=0 INNER JOIN device_rate_plan AS d ON TRIM(assets.DEVICE_PLAN_ID)=d.PLAN_NAME AND d.ACCOUNT_ID=b.ID AND d.DELETED=0 INNER JOIN device_plan_to_service_apn_mapping as e on e.DEVICE_PLAN_ID_ID=d.ID INNER JOIN Service_Apn_ip as f on assets.IP_ADDRESS=f.APN_IP");
-- select @getsapndet_list;
PREPARE stmt_1 FROM @getdp_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;

SET @upddp_list = CONCAT("UPDATE device_rate_plan as dp SET dp.STATUS=1 WHERE dp.ID IN (",@dp_list,") AND (dp.STATUS=0 OR dp.STATUS IS NULL);");
-- select @getsapndet_list;
PREPARE stmt_1 FROM @upddp_list;
EXECUTE stmt_1;
DEALLOCATE   PREPARE stmt_1;



SET @ai := (select max(id)+1 from assets);
set @qry = concat('alter table assets auto_increment=',@ai);
prepare stmt from @qry; execute stmt;

SET @aiex := (select max(id)+1 from assets_extended);
set @qryex = concat('alter table assets_extended auto_increment=',@aiex);
prepare stmt from @qryex; execute stmt;

COMMIT;

DELETE n1 FROM service_apn_account_mapping n1, service_apn_account_mapping n2 WHERE n1.id < n2.id AND n1.ACCOUNT_ID = n2.ACCOUNT_ID AND n1.APN_ID = n2.APN_ID ;

END IF;

SELECT CONCAT('before_excution: ',IFNULL(@before_excution,0)) as before_excution,
CONCAT('after_execution: ',IFNULL(@after_execution,0)) as after_execution,
CONCAT('success_count: ',IFNULL(@success_count,0)) as success_count,
CONCAT('failed_count: ',IFNULL(@failed_count,0)) as failed_count,
IFNULL(@MESSAGE_TEXT,'') as Remarks;


END//
DELIMITER ;

